import { Villa, DiningVenue, Experience } from '@/types';

export const villas: Villa[] = [
  {
    id: 'two-bed-ocean-suite-pool',
    name: 'Two-Bedroom Ocean Suite with Pool',
    slug: 'two-bedroom-ocean-suite-pool',
    category: 'ocean-suite',
    tagline: 'Expansive oceanfront living for families and groups',
    description: 'The ultimate in overwater luxury, these magnificent suites span two levels with panoramic ocean views, two master bedrooms each with ensuite bathrooms, a generous living area, and a private infinity pool that seems to merge with the Indian Ocean horizon.',
    features: ['Two master bedrooms', 'Private infinity pool', 'Panoramic ocean views', 'Living & dining area', 'Butler service', 'Direct ocean access', 'Outdoor shower', 'Bose sound system'],
    maxGuests: 6,
    bedrooms: 2,
    size: '340 sqm',
    images: ['/villas/two-bed-ocean-suite.jpg'],
    hasPool: true,
    hasWhirlpool: false,
    viewType: 'ocean',
  },
  {
    id: 'one-bed-ocean-suite-pool',
    name: 'One-Bedroom Ocean Suite with Pool',
    slug: 'one-bedroom-ocean-suite-pool',
    category: 'ocean-suite',
    tagline: 'Intimate oceanfront luxury with private pool',
    description: 'Perched above the crystalline waters, this stunning suite offers a spacious bedroom, a private infinity pool, and floor-to-ceiling windows that frame endless ocean panoramas. The perfect sanctuary for couples seeking refined overwater living.',
    features: ['Private infinity pool', 'Ocean panorama', 'King-size bed', 'Freestanding bathtub', 'Butler service', 'Sun deck', 'Outdoor shower'],
    maxGuests: 3,
    bedrooms: 1,
    size: '220 sqm',
    images: ['/villas/one-bed-ocean-suite.jpg'],
    hasPool: true,
    hasWhirlpool: false,
    viewType: 'ocean',
  },
  {
    id: 'oceanfront-pool-villa',
    name: 'Oceanfront Pool Villa',
    slug: 'oceanfront-pool-villa',
    category: 'beach',
    tagline: 'Where the beach meets your private paradise',
    description: 'Step directly from your villa onto powdery white sand with the turquoise lagoon stretching before you. A generous private pool, lush tropical gardens, and an open-air bathroom create a seamless connection between luxury and nature.',
    features: ['Private pool', 'Direct beach access', 'Tropical garden', 'Open-air bathroom', 'Sun loungers', 'Outdoor dining', 'Nespresso machine'],
    maxGuests: 3,
    bedrooms: 1,
    size: '185 sqm',
    images: ['/villas/oceanfront-pool.jpg'],
    hasPool: true,
    hasWhirlpool: false,
    viewType: 'ocean',
  },
  {
    id: 'water-villa-whirlpool',
    name: 'Water Villa with Whirlpool',
    slug: 'water-villa-whirlpool',
    category: 'overwater',
    tagline: 'Overwater bliss with private whirlpool',
    description: 'Floating above the turquoise lagoon, this elegant water villa features a private whirlpool on your sundeck, glass floor panels for observing marine life below, and direct ladder access to the warm Indian Ocean waters.',
    features: ['Private whirlpool', 'Glass floor panels', 'Ocean access ladder', 'Sun deck', 'Rain shower', 'Lagoon views', 'Minibar'],
    maxGuests: 3,
    bedrooms: 1,
    size: '140 sqm',
    images: ['/villas/water-villa-whirlpool.jpg'],
    hasPool: false,
    hasWhirlpool: true,
    viewType: 'lagoon',
  },
  {
    id: 'two-bed-beach-villa-pools',
    name: 'Two-Bedroom Beach Villa with Two Pools',
    slug: 'two-bedroom-beach-villa-pools',
    category: 'beach',
    tagline: 'A private beachfront estate with dual pools',
    description: 'This expansive beachfront retreat offers two luxurious bedrooms, two private pools, lush tropical gardens, and direct access to a pristine stretch of white sand. Ideal for families or couples traveling together who desire space and privacy.',
    features: ['Two private pools', 'Two bedrooms with ensuite', 'Beach access', 'Tropical garden', 'Outdoor dining pavilion', 'Butler service', 'Children welcome'],
    maxGuests: 6,
    bedrooms: 2,
    size: '380 sqm',
    images: ['/villas/two-bed-beach.jpg'],
    hasPool: true,
    hasWhirlpool: false,
    viewType: 'ocean',
  },
  {
    id: 'sunset-deluxe-beach-pool',
    name: 'Sunset Deluxe Beach Pool Villa',
    slug: 'sunset-deluxe-beach-pool-villa',
    category: 'beach',
    tagline: 'Premium sunset views with deluxe finishes',
    description: 'Positioned on the western shoreline for uninterrupted sunset views, this deluxe villa features premium furnishings, a generous private pool, and an elevated outdoor lounge. Watch the Maldivian sky transform into gold and crimson each evening from your private terrace.',
    features: ['Premium sunset views', 'Private pool', 'Elevated lounge', 'King-size bed', 'Outdoor rain shower', 'Premium minibar', 'Telescope'],
    maxGuests: 3,
    bedrooms: 1,
    size: '200 sqm',
    images: ['/villas/sunset-deluxe.jpg'],
    hasPool: true,
    hasWhirlpool: false,
    viewType: 'sunset',
  },
  {
    id: 'sunset-beach-pool',
    name: 'Sunset Beach Pool Villa',
    slug: 'sunset-beach-pool-villa',
    category: 'beach',
    tagline: 'Golden hour, every hour',
    description: 'Enjoy the romance of the western Maldivian sunset from your private beach villa. With a plunge pool, outdoor terrace, and elegant interiors inspired by yacht-life living, this villa captures the essence of the resort.',
    features: ['Sunset views', 'Private plunge pool', 'Beach access', 'Outdoor terrace', 'Nautical-inspired decor', 'Rain shower', 'Espresso machine'],
    maxGuests: 3,
    bedrooms: 1,
    size: '170 sqm',
    images: ['/villas/sunset-beach.jpg'],
    hasPool: true,
    hasWhirlpool: false,
    viewType: 'sunset',
  },
  {
    id: 'deluxe-beach-pool',
    name: 'Deluxe Beach Pool Villa',
    slug: 'deluxe-beach-pool-villa',
    category: 'beach',
    tagline: 'Elevated beachfront luxury',
    description: 'A refined take on beachfront living with enhanced amenities, a private pool surrounded by tropical foliage, and direct access to the pristine beach. The open-plan design seamlessly blends indoor comfort with outdoor paradise.',
    features: ['Private pool', 'Beach access', 'Open-plan design', 'Tropical garden', 'Outdoor dining', 'Premium bath amenities', 'Smart controls'],
    maxGuests: 3,
    bedrooms: 1,
    size: '190 sqm',
    images: ['/villas/deluxe-beach.jpg'],
    hasPool: true,
    hasWhirlpool: false,
    viewType: 'lagoon',
  },
  {
    id: 'water-villa',
    name: 'Water Villa',
    slug: 'water-villa',
    category: 'overwater',
    tagline: 'Classic overwater living',
    description: 'Experience the iconic Maldivian overwater villa with a contemporary nautical twist. Perched above the turquoise lagoon with a spacious sun deck, glass floor panels, and direct ocean access — the quintessential island escape.',
    features: ['Overwater deck', 'Glass floor panels', 'Ocean access', 'Lagoon views', 'Rain shower', 'Daybed', 'Nespresso machine'],
    maxGuests: 3,
    bedrooms: 1,
    size: '120 sqm',
    images: ['/villas/water-villa.jpg'],
    hasPool: false,
    hasWhirlpool: false,
    viewType: 'lagoon',
  },
  {
    id: 'beach-villa',
    name: 'Beach Villa',
    slug: 'beach-villa',
    category: 'beach',
    tagline: 'Where tropical dreams begin',
    description: 'Nestled among coconut palms with direct access to a pristine white sand beach, this villa offers an authentic Maldivian experience with contemporary comforts. The perfect introduction to island paradise living.',
    features: ['Beach access', 'Tropical garden', 'Outdoor bathroom', 'Sun loungers', 'Rain shower', 'Ceiling fan terrace', 'Welcome amenities'],
    maxGuests: 3,
    bedrooms: 1,
    size: '110 sqm',
    images: ['/villas/beach-villa.jpg'],
    hasPool: false,
    hasWhirlpool: false,
    viewType: 'lagoon',
  },
];

export const diningVenues: DiningVenue[] = [
  {
    id: 'bageecha',
    name: 'Bageecha',
    cuisine: 'International',
    description: 'The resort\'s all-day dining restaurant offering a lavish buffet breakfast and themed dinner evenings featuring cuisines from around the world.',
    image: '/dining/bageecha.jpg',
    hours: '7:00 AM – 10:30 PM',
    highlight: 'Live cooking stations',
  },
  {
    id: 'the-lagoon',
    name: 'The Lagoon',
    cuisine: 'Seafood & Grill',
    description: 'Set over the lagoon with stunning water views, specializing in the freshest catches grilled to perfection alongside premium meats and local flavors.',
    image: '/dining/lagoon.jpg',
    hours: '12:00 PM – 10:30 PM',
    highlight: 'Overwater dining',
  },
  {
    id: 'al-tramonto',
    name: 'Ristorante al Tramonto',
    cuisine: 'Italian',
    description: 'Authentic Italian cuisine crafted with imported and local ingredients, served in an elegant setting with panoramic sunset views over the Indian Ocean.',
    image: '/dining/al-tramonto.jpg',
    hours: '6:30 PM – 10:30 PM',
    highlight: 'Sunset views',
  },
  {
    id: 'fukuya',
    name: 'Fukuya Teppanyaki',
    cuisine: 'Japanese',
    description: 'An intimate teppanyaki experience where skilled chefs perform culinary artistry before your eyes, using the finest seafood and Wagyu beef.',
    image: '/dining/fukuya.jpg',
    hours: '6:30 PM – 10:30 PM',
    highlight: 'Live teppanyaki show',
  },
  {
    id: 'hook',
    name: 'Hook',
    cuisine: 'Seafood',
    description: 'A casual yet refined seafood restaurant celebrating the ocean\'s bounty. From line-caught tuna to Maldivian lobster, every dish tells a story of the sea.',
    image: '/dining/hook.jpg',
    hours: '12:00 PM – 10:30 PM',
    highlight: 'Catch of the day',
  },
  {
    id: 'captains-bar',
    name: 'Captain\'s Bar',
    cuisine: 'Cocktails & Tapas',
    description: 'The social heart of the resort, this nautical-themed bar serves signature cocktails, fine wines, and tapas in a glamorous atmosphere reminiscent of a luxury yacht club.',
    image: '/dining/captains-bar.jpg',
    hours: '5:00 PM – 12:00 AM',
    highlight: 'Signature rum cocktails',
  },
];

export const experiences: Experience[] = [
  {
    id: 'crows-nest',
    name: 'Crow\'s Nest',
    description: 'Ascend the spiral staircase to the resort\'s iconic lookout point. Sip rum cocktails as you survey the endless Indian Ocean panorama.',
    image: '/experiences/crows-nest.jpg',
    category: 'dining',
  },
  {
    id: 'araamu-spa',
    name: 'Araamu Spa',
    description: 'A tranquil sanctuary surrounded by tropical gardens offering traditional and modern treatments designed to restore balance and vitality.',
    image: '/experiences/spa.jpg',
    category: 'wellness',
  },
  {
    id: 'diving',
    name: 'Scuba Diving',
    description: 'Explore pristine coral reefs and encounter manta rays, whale sharks, and vibrant marine life with our PADI-certified dive center.',
    image: '/experiences/diving.jpg',
    category: 'water',
  },
  {
    id: 'seawall-picnic',
    name: 'Seawall Specialities',
    description: 'A curated picnic basket experience on the seawall — gourmet bites, champagne, and the Indian Ocean as your dining companion.',
    image: '/experiences/seawall.jpg',
    category: 'dining',
  },
  {
    id: 'sunset-cruise',
    name: 'Sunset Dolphin Cruise',
    description: 'Set sail as the golden hour transforms the sky, spotting pods of playful dolphins against the backdrop of a Maldivian sunset.',
    image: '/experiences/dolphin-cruise.jpg',
    category: 'adventure',
  },
  {
    id: 'captains-class',
    name: 'Captain\'s Class',
    description: 'Learn the art of seafaring — from tying nautical knots to reading the stars — in this hands-on maritime experience.',
    image: '/experiences/captains-class.jpg',
    category: 'culture',
  },
];

export const AGENT_INFO = {
  name: 'Reservations & Sales',
  tagline: 'Official Booking Partner',
  copyright: 'Reservations & Sales',
  phone: '+960 664 1010',
  email: 'reservations@villanautica.com',
};

export const RESORT_INFO = {
  name: 'Villa Nautica',
  fullName: 'Villa Nautica Maldives Resort',
  location: 'Paradise Island, North Malé Atoll, Maldives',
  tagline: 'Celebrate the glamour of cosmopolitan quayside living',
  transferTime: '20 minutes by speedboat from Velana International Airport',
  phone: '+960 664 1010',
  email: 'reservations@villanautica.com',
  whatsapp: '+960 773 0000',
  checkIn: '2:00 PM',
  checkOut: '12:00 PM',
  totalVillas: 10,
  restaurants: 9,
  coordinates: { lat: 4.2566, lng: 73.5333 },
};
